// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCitWDGPOKc1nJGxmyWwnIHkvGqxdfDulg',
    appId: '1:44859872881:web:b4ea2b36b943418b452dd0',
    messagingSenderId: '44859872881',
    projectId: 'glamzy-app',
    authDomain: 'glamzy-app.firebaseapp.com',
    storageBucket: 'glamzy-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeVUnTg8yxXMMiJ9P9IVl0SoVj3Z-lLRs',
    appId: '1:44859872881:android:ad2158347a6f8981452dd0',
    messagingSenderId: '44859872881',
    projectId: 'glamzy-app',
    storageBucket: 'glamzy-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKJzVG6wR5Tm11rEG4OVzTGagfqNaDsmA',
    appId: '1:44859872881:ios:12bcc3c485c7b55b452dd0',
    messagingSenderId: '44859872881',
    projectId: 'glamzy-app',
    storageBucket: 'glamzy-app.firebasestorage.app',
    iosBundleId: 'com.example.graduation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKJzVG6wR5Tm11rEG4OVzTGagfqNaDsmA',
    appId: '1:44859872881:ios:12bcc3c485c7b55b452dd0',
    messagingSenderId: '44859872881',
    projectId: 'glamzy-app',
    storageBucket: 'glamzy-app.firebasestorage.app',
    iosBundleId: 'com.example.graduation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCitWDGPOKc1nJGxmyWwnIHkvGqxdfDulg',
    appId: '1:44859872881:web:362dd96deb475520452dd0',
    messagingSenderId: '44859872881',
    projectId: 'glamzy-app',
    authDomain: 'glamzy-app.firebaseapp.com',
    storageBucket: 'glamzy-app.firebasestorage.app',
  );
}
